### ISSUE TITLE
`NotifictionService` -> `NotificationService`

### ISSUE THREAD

**Issue by robloo** [DamianSuess/Test.PrismXF#11]
Spelling error in the class and interface naming here: https://github.com/DamianSuess/Learn.PrismLibrary/tree/master/Avalonia-Ex3-SplitView/Services. Just missing an 'a' in both files.

Great examples though!

**Comment by DamianSuess** [comment]
Thank you, @robloo! Wow, that's embarrassing. Even more so, I had to read it 2 times over to find the missing `a` 😄
